# Generated by Django 3.1.5 on 2021-01-28 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (5, 'Fourth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eighth')])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('admission_date', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.section')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='hod',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_of', to='administration.teacher'),
        ),
    ]
